Repository ucsb-cs156-s21/proj-ucsb-courses-search, pull requests merged in 2020-12, with the labels that each got.

#75 5pm a search by ge
  javascript/src/main/App.js
  javascript/src/main/components/BasicCourseSearch/GeCourseSearchForm.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/History/Ge.js
  javascript/src/main/services/courseSearches.js
  javascript/src/test/components/BasicCourseSearch/GeCourseSearchForm.test.js
  javascript/src/test/pages/History/Ge.test.js
  javascript/src/test/services/courseSearches.test.js
  package-lock.json
  src/main/java/edu/ucsb/courses/controllers/GeSearchController.java
  src/main/java/edu/ucsb/courses/repositories/ArchivedCourseRepository.java
  src/test/java/edu/ucsb/courses/controllers/GeSearchControllerTests.java
Labels: f20-5pm-a

#73 5pm-a-search-by-course-name
  javascript/package-lock.json
  javascript/src/main/App.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/History/CourseName.js
  javascript/src/main/services/courseSearches.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
  javascript/src/test/pages/History/CourseName.test.js
  javascript/src/test/services/courseSearches.test.js
  src/main/java/edu/ucsb/courses/controllers/HistorySearchCourseQtrController.java
  src/main/java/edu/ucsb/courses/repositories/ArchivedCourseRepository.java
  src/test/java/edu/ucsb/courses/controllers/HistorySearchCourseQtrControllerTests.java
Labels: f20-5pm-a

#77 5pm d add sections days and times
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
  javascript/src/test/utils/BasicCourseTableHelpers.test.js
Labels: f20-5pm-d

#67 5pm d add basic courses table
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
  javascript/src/test/utils/BasicCourseTableHelpers.test.js
Labels: f20-5pm-d

#81 5pm-a-course-search-by-name-code-cleanup
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/pages/History/CourseName.js
  src/test/java/edu/ucsb/courses/controllers/HistorySearchCourseQtrControllerTests.java
Labels: f20-5pm-a

#76 5pm c avg class size by dept
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/ClassSizeForm.js
  javascript/src/main/components/Statistics/ClassSizeTable.js
  javascript/src/main/components/Statistics/ClassSizeTable.test.js
  javascript/src/main/components/Statistics/DepartmentFormSelect.js
  javascript/src/main/components/Statistics/QuarterFormSelect.js
  javascript/src/main/pages/Statistics/ClassSize.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/ClassSizeForm.test.js
  javascript/src/test/components/Statistics/DepartmentFormSelect.test.js
  javascript/src/test/components/Statistics/QuarterFormSelect.test.js
  javascript/src/test/pages/Statistics/ClassSize.test.js
  javascript/src/test/services/statisticService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/AvgClassSize.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/AvgClassSizeTests.java
Labels: F20-5pm-c, READY for STAFF REVIEW

#66 Kh/dc,csv download
  javascript/package-lock.json
  javascript/package.json
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/Nav/LogoutButton.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  pom.xml
  src/main/java/edu/ucsb/courses/controllers/BasicSearchController.java
  src/test/java/edu/ucsb/courses/controllers/BasicSearchControllerTests.java
Labels: READY for STAFF REVIEW, f20-5pm-d

#72 5pm-c Course Occupancy by Division
  javascript/src/main/App.js
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/DepartmentFormSelect.js
  javascript/src/main/components/Statistics/DivisionOccupancyForm.js
  javascript/src/main/components/Statistics/DivisionOccupancyTable.js
  javascript/src/main/pages/Statistics/DivisionOccupancy.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/DivisionOccupancyForm.test.js
  javascript/src/test/components/Statistics/DivisionOccupancyTable.test.js
  javascript/src/test/components/Statistics/QuarterFormSelect.test.js
  javascript/src/test/pages/Statistics/DivisionOccupancy.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/DivisionOccupancy.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/DivisionOccupancyTests.java
Labels: F20-5pm-c, READY for STAFF REVIEW

#85 5pm b schedule crud operations
  javascript/src/main/components/Schedule/AddSchedForm.js
  javascript/src/main/components/Schedule/ScheduleSearchForm.js
  javascript/src/main/pages/Schedule/Schedule.js
  javascript/src/main/services/scheduleAPI.js
  javascript/src/test/components/Schedule/AddSchedForm.test.js
  javascript/src/test/components/Schedule/ScheduleCoursesTable.test.js
  javascript/src/test/components/Schedule/ScheduleSearchForm.test.js
  javascript/src/test/pages/Statistics/Statistics.test 2.js
  javascript/src/test/services/scheduleAPI.test.js
  src/main/java/edu/ucsb/courses/controllers/ScheduleController.java
  src/main/java/edu/ucsb/courses/controllers/ScheduleItemController.java
  src/main/java/edu/ucsb/courses/entities/ScheduleItem.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleControllerTests.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleItemControllerTests.java
Labels: FIX ME, f20-5pm-b

#86 5pm b create menu item personal schedule
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Nav/ScheduleButton.js
  javascript/src/main/components/Nav/ScheduleNav.js
  javascript/src/main/pages/Schedule/Schedule.js
  javascript/src/test/components/Nav/ScheduleNav.test.js
  javascript/src/test/pages/Schedule/Schedule.test.js
  src/main/.DS_Store
Labels: READY for STAFF REVIEW, f20-5pm-b

#69 jv - add course occupancy by department statistics page
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/CourseOccupancyForm.js
  javascript/src/main/components/Statistics/CourseOccupancyTable.js
  javascript/src/main/pages/Statistics/CourseOccupancy.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/CourseOccupancyForm.test.js
  javascript/src/test/components/Statistics/CourseOccupancyTable.test.js
  javascript/src/test/pages/Statistics/CourseOccupancy.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/QuarterOccupancy.java
  src/main/java/edu/ucsb/courses/repositories/ArchivedCourseRepository.java
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/QuarterOccupancyTests.java
Labels: F20-5pm-c, READY for STAFF REVIEW

#89 5pm b schedule entity and repository with controller
  src/main/java/edu/ucsb/courses/controllers/ScheduleController.java
  src/main/java/edu/ucsb/courses/entities/Schedule.java
  src/main/java/edu/ucsb/courses/repositories/ScheduleRepository.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleControllerTests.java
  src/test/java/edu/ucsb/courses/entities/ScheduleTests.java
Labels: READY for STAFF REVIEW, f20-5pm-b

#95 5pm b schedule frontend user interface
  javascript/package-lock.json
  javascript/package.json
  javascript/src/index.js
  javascript/src/main/App.js
  javascript/src/main/components/Loading/Loading.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Schedule/AddSchedForm.js
  javascript/src/main/components/Schedule/ScheduleSearchForm.js
  javascript/src/main/components/Schedule/ScheduleTable.js
  javascript/src/main/pages/Schedule/EditSchedule.js
  javascript/src/main/pages/Schedule/NewSchedule.js
  javascript/src/main/pages/Schedule/Schedule.js
  javascript/src/main/services/Schedule/scheduleServices.js
  javascript/src/test/components/Schedule/AddSchedForm.test.js
  javascript/src/test/components/Schedule/ScheduleCoursesTable.test.js
  javascript/src/test/components/Schedule/ScheduleSearchForm.test.js
  javascript/src/test/components/Schedule/ScheduleTable.test.js
  javascript/src/test/pages/Schedule/EditSchedule.test.js
  javascript/src/test/pages/Schedule/NewSchedule.test.js
  javascript/src/test/pages/Schedule/Schedule.test.js
  javascript/src/test/services/scheduleServices.test.js
  src/main/java/edu/ucsb/courses/controllers/ScheduleController.java
  src/main/java/edu/ucsb/courses/controllers/ScheduleItemController.java
  src/main/java/edu/ucsb/courses/entities/ScheduleItem.java
  src/main/java/edu/ucsb/courses/repositories/ScheduleItemRepository.java
  src/main/java/edu/ucsb/courses/repositories/ScheduleRepository.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleControllerTests.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleItemControllerTests.java
  src/test/java/edu/ucsb/courses/entities/ScheduleItemTests.java
Labels: 10, 40, TEAM-DONE, f20-5pm-b
