Repository ucsb-cs156-s21/proj-ucsb-courses-search, pull requests merged in 2021-02, with the labels that each got.

#71 5pm-c-Num full courses by department
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/FullCourseTable.js
  javascript/src/main/components/Statistics/FullCoursesForm.js
  javascript/src/main/pages/Statistics/NumFullCoursesByDept.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/FullCourseTable.test.js
  javascript/src/test/components/Statistics/FullCoursesForm.test.js
  javascript/src/test/pages/Statistics/NumFullCoursesByDept.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/FullCourse.java
  src/main/java/edu/ucsb/courses/repositories/ArchivedCourseRepository.java
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/FullCourseTests.java
Labels: F20-5pm-c, READY for STAFF REVIEW, TEAM-DONE

#134 AL - Set Actions fetch depth to 2 to fix Codecov reports
  .github/workflows/tests-and-coverage.yml
Labels: Staff-pr

#90 5pm b schedule items entitiy repository controller
  src/main/java/edu/ucsb/courses/entities/ScheduleItem.java
Labels: f20-5pm-b

#132 AL - Add S21 quarter to basic search
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
Labels: Staff-pr

#133 AL - Add S21 quarter for archived searches
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormInstructor.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
  javascript/src/main/components/BasicCourseSearch/GeCourseSearchForm.js
Labels: Staff-pr

#144 AL - Remove unneeded package-lock file
  package-lock.json
Labels: Staff-pr

#138 Staff w21 add subjects api endpoint
  src/main/java/edu/ucsb/courses/controllers/SubjectAreasController.java
  src/main/java/edu/ucsb/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/courses/controllers/SubjectAreasControllerTests.java
  src/test/java/edu/ucsb/courses/services/UCSBCurriculumServiceTest.java
Labels: Staff-pr

#146 AL - Add bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Staff-pr

#142 Staff w21 add storybook
  .gitignore
  README.md
  javascript/.storybook/main.js
  javascript/.storybook/preview.js
  javascript/package-lock.json
  javascript/package.json
  javascript/src/index.js
  javascript/src/main/fixtures/Courses/courseFixtures.js
  javascript/src/stories/components/BasicCourseSearch/BasicCourseTable.stories.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: Staff-pr

#130 5pm-4: Remove "From MongoDB" from the title of basic search and Add Data Description
  javascript/src/main/pages/History/Basic.js
  javascript/src/test/pages/History/Basic.test.js
Labels: w21-5pm-4

#127 qh,aa - Left align name and description fields
  javascript/src/main/components/Schedule/ScheduleTable.js
Labels: MISSING TEAM CR, w21-5pm-1

#131 5pm-4: Updated Navbar to toggle on small viewports
  javascript/src/main/components/Nav/AppNavbar.js
Labels: w21-5pm-4

#128 5pm 3 add instructor last name
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormInstructor.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchFormInstructor.test.js
Labels: w21-5pm-3

#129 sht, jl - fix footer content
  javascript/src/main/components/Footer/AppFooter.js
  javascript/src/test/components/Footer/AppFooter.test.js
Labels: w21-5pm-1

#155 ds/mr - updated title for main index page
  javascript/public/index.html
Labels: 5, w21-5pm-3

#161 5pm 4 fix nav bar profile
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Nav/AuthNav.js
  javascript/src/main/components/Nav/ProfileButton.js
  javascript/src/main/components/Nav/ProfileNav.js
  javascript/src/test/components/Nav/AppNavbar.test.js
  javascript/src/test/components/Nav/AuthNav.test.js
  javascript/src/test/components/Nav/ProfileNav.test.js
Labels: FIX ME-failing tests, w21-5pm-4

#160 5pm 1 add header
  javascript/src/main/pages/Statistics/ClassSize.js
  javascript/src/test/pages/Statistics/ClassSize.test.js
Labels: w21-5pm-1

#147 Allow selection of any subject area on basic search
  javascript/package.json
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/BasicCourseSearch/SelectSubject.js
  javascript/src/main/fixtures/Courses/subjectFixtures.js
  javascript/src/main/services/courseSearches.js
  javascript/src/main/services/subjectAreaService.js
  javascript/src/main/utils/sortHelper.js
  javascript/src/stories/components/BasicCourseSearch/BasicCourseSearchForm.stories.js
  javascript/src/stories/components/BasicCourseSearch/SelectSubject.stories.js
  javascript/src/test/App.test.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
  javascript/src/test/components/BasicCourseSearch/SelectSubject.test.js
  javascript/src/test/pages/Home/Home.test.js
  javascript/src/test/services/subjectAreaService.test.js
  javascript/src/test/utils/sortHelper.test.js
  src/main/java/edu/ucsb/courses/controllers/SubjectAreasController.java
Labels: Staff-pr
