Repository ucsb-cs156-s21/proj-ucsb-courses-search, pull requests merged in 2021-05, with the labels that each got.

#259 wl, ba 5pm-3 - changed size of header to match the others
  javascript/src/main/pages/History/Basic.js
Labels: s21-5pm-3

#260 Implemented a 5-second auto-dismiss on toast notifications
  javascript/src/index.js
Labels: s21-5pm-1

#266 IG EY - Fixed the red and yellow colors for courses search and factored out color definitions.
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/BasicCourseSearch/TableLegend.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: s21-5pm-4

#261 Finished reordering About, Search, Statistics, Profile
  javascript/package-lock.json
  javascript/src/main/components/Nav/AppNavbar.js
Labels: s21-5pm-3

#263 Deploy New Favicon with Storke Image Kevin Sheldin
  javascript/public/favicon.ico
  javascript/public/index.html
  secrets-heroku.properties.SAMPLE
  secrets-localhost.properties.SAMPLE
Labels: s21-5pm-4

#262 ey/lw 5pm-1 Add a brief description to the Admin Settings page
  javascript/src/main/pages/Admin/AdminSettings.jsx
  javascript/src/test/pages/Admin/Settings.test.js
Labels: s21-5pm-1

#271 ss/aa 5pm-1 - Standardized field names on create schedule page
  javascript/src/main/components/Schedule/AddSchedForm.js
Labels: s21-5pm-1

#265 SL/CO - 5pm-2 - Search by Course Name shows an example of a course number input (#213)
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/pages/History/CourseName.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
Labels: s21-5pm-2

#269 5pm 4 checkbox text
  javascript/.env.local.SAMPLE
  javascript/src/main/components/BasicCourseSearch/CourseFilters.js
  secrets-heroku.properties.SAMPLE
  secrets-localhost.properties.SAMPLE
Labels: s21-5pm-4

#270 kt - 5pm-2 - Search by Course Name changed to Search by Course Number
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
Labels: s21-5pm-2

#272 mm/sa 5pm-2 - Remove Jumbotron tags in TableLegend.js
  javascript/src/main/components/BasicCourseSearch/TableLegend.js
Labels: s21-5pm-2

#285 IG MH - fixed the issue where basic history search was not returning any results
  javascript/src/main/services/courseSearches.js
Labels: FIX ME-MISSING TEAM CR, s21-5pm-4

#281 5pm-3 TP Added code so that the Home page and Basic Search page now shows Fall 2008 to Spring 2021 instead of a hard coded list of 3 quarters
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseSearchForm.test.js
Labels: Frontend, S21-Refactoring, s21-5pm-3-refactor

#291 5PM-1 EY/MR - add Danger checks for common PR mistakes
  .github/workflows/contribution-requirements.yml
  dangerfile.js
Labels: s21-5pm-1-sched

#279 5pm-3 DW Added code to BasicSearchForm to save Quarter/Department/Level values to localStorage so user selections remain when leaving the page
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/BasicCourseSearch/SelectQuarter.js
  javascript/src/main/components/BasicCourseSearch/SelectSubject.js
Labels: s21-5pm-3-refactor

#295 5pm-4 Added table formatting to the /history/basic route search results
  javascript/src/main/pages/History/Basic.js
  javascript/src/test/pages/History/Basic.test.js
Labels: s21-5pm-4-stats

#278 5pm-3 KDBCT Added code to save Quarter/Subject on Search->Basic Search page so that user selections will remain the same when they return to the site.
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
  javascript/src/main/components/BasicCourseSearch/SelectQuarter.js
Labels: s21-5pm-3-refactor

#268 pc - add instructions to Personal Schedule page
  javascript/src/main/pages/Schedule/Schedule.js
Labels: S21-staff

#300 az/lw 5pm-1 Implemented get, new, delete methods for scheduleItem
  src/main/java/edu/ucsb/courses/controllers/ScheduleItemController.java
  src/main/java/edu/ucsb/courses/repositories/ScheduleRepository.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleItemControllerTests.java
Labels: s21-5pm-1-sched

#301 IG MH - added enrolled and course capacity columns to display in the BasicCourseTable
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: s21-5pm-4-stats

#292 mm/sl 5pm-2 - Give sections italic font instead of regular
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
Labels: FIX ME-please respond to code review, s21-5pm-2-search

#297 5pm-2 kt - Make table of course search results invisible initially and if there are no search results
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: s21-5pm-2-search

#282 5pm-3 TP - Added QuarterSelector for every Search Page
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormInstructor.js
  javascript/src/main/components/BasicCourseSearch/GeCourseSearchForm.js
Labels: Frontend, S21-Refactoring, s21-5pm-3-refactor

#306 IG MH - Fixed bug where day/time columns were sometimes displaying null-null instead of TBD
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
Labels: FIX ME-MISSING TEAM CR, s21-5pm-4-stats

#299 5pm-3 Refactor In SelectQuarter Component using localStorage277
  javascript/src/main/components/BasicCourseSearch/SelectQuarter.js
Labels: Frontend, s21-5pm-3-refactor

#307 5pm 3 refactor csv download code on home page
  javascript/src/main/pages/History/Basic.js
  javascript/src/main/pages/Home/Home.js
Labels: s21-5pm-3-refactor

#314 5pm-3-switch basic search and search by course number from a hard coded list of subjects to use selectSubject.
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
  javascript/src/main/services/courseSearches.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.test.js
  javascript/src/test/services/courseSearches.test.js
Labels: s21-5pm-3-refactor

#332 5pm-3 Refactor BasicCourse Level
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/BasicCourseSearch/SelectLevel.js
Labels: Frontend, s21-5pm-3-refactor

#336 ey/ss - 5pm 1 get schedule items by schedule id
  src/main/java/edu/ucsb/courses/controllers/ScheduleController.java
  src/main/java/edu/ucsb/courses/models/PersonalSchedule.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleControllerTests.java
  src/test/java/edu/ucsb/courses/models/PersonalScheduleTests.java
Labels: S21-pers-sched, s21-5pm-1-sched

#335 kt - 5pm-2 - Improve home page search to see results without scrolling
  javascript/src/main/App.css
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
Labels: FIX ME-MISSING TEAM CR, s21-5pm-2-search

#330 5pm-2 CO List times in 12 hour format by incorporating a third-party date formatter
  javascript/package-lock.json
  javascript/package.json
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: 10, 20, s21-5pm-2-search

#327 5pm-2 kt - fix BasicCourseSearchForm in the storybook
  javascript/src/stories/components/BasicCourseSearch/BasicCourseSearchForm.stories.js
Labels: READY for STAFF REVIEW, s21-5pm-2-search

#346 mm/sa 5pm-2 Refactor CSS styling of Section Rows for Maintainability
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/BasicCourseSearch/TableLegend.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
Labels: s21-5pm-2-search

#331 az/mr/lw 5pm-1-Redirects user to add schedule page after clicking on 'Add' button
  javascript/src/main/App.js
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/Schedule/AddToScheduleTable.js
  javascript/src/main/pages/Schedule/AddToSchedule.js
  javascript/src/test/components/Schedule/AddToScheduleTable.test.js
  javascript/src/test/pages/Schedule/AddToSchedule.test.js
Labels: s21-5pm-1-sched

#344 aa/az 5pm-1 removed the ability to add classes when not an admin or member
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: s21-5pm-1-sched

#319 sl - 5pm-2 - Remove Course JSON Response from all search pages
  javascript/src/main/components/Utilities/JSONPrettyCard.js
  javascript/src/main/pages/History/Basic.js
  javascript/src/main/pages/History/Ge.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/stories/components/Utilities/JSONPrettyPanel.stories.js
  javascript/src/test/components/Utilities/JSONPrettyCard.test.js
Labels: S21, S21-search-ui, s21-5pm-2-search

#339 5pm 4 statistics page to search for summary
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/AggregateStatisticsTable.js
  javascript/src/main/components/Statistics/SingleCourseSectionForm.js
  javascript/src/main/components/Statistics/SingleCourseSectionTable.js
  javascript/src/main/pages/Statistics/SingleCourseSearch.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/SingleCourseSearchForm.test.js
  javascript/src/test/components/Statistics/SingleCourseSearchTable.test.js
  javascript/src/test/pages/Statistics/SingleCourseSearch.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/SingleCourseSearch.java
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/SingleCourseSearchTests.java
Labels: FIX ME-MISSING TEAM CR, s21-5pm-4-stats
