Repository ucsb-cs156-s21/proj-ucsb-courses-search, pull requests merged in 2021-03, with the labels that each got.

#166 5pm 2 favicon
  javascript/public/apple-touch-icon.png
  javascript/public/favicon-16x16.png
  javascript/public/favicon-32x32.png
  javascript/public/favicon.ico
  javascript/public/index.html
  javascript/public/logo192.png
  javascript/public/logo512.png
  javascript/public/manifest.json
Labels: 5, w21-5pm-2

#167 5pm 3 total courses by dept
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/TotalCoursesForm.js
  javascript/src/main/components/Statistics/TotalCoursesTable.js
  javascript/src/main/pages/Statistics/TotalCourses.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/TotalCoursesForm.test.js
  javascript/src/test/components/Statistics/TotalCoursesTable.test.js
  javascript/src/test/pages/Statistics/TotalCourses.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/TotalCoursesDept.java
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/TotalCoursesDeptTest.java
Labels: FIX ME-code review issues, w21-5pm-3

#149 5pm 3 - Fix spacing of "Submit" & "Download CSV" buttons on Home
  javascript/src/main/pages/Home/Home.js
Labels: w21-5pm-3

#168 5pm-4: Combine number and suffix fields in Course Name Search
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
Labels: w21-5pm-4

#153 jj/am - aligned section results table to the left
  javascript/package-lock.json
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: 5, w21-5pm-2

#172 5pm 1 - Add bootstrap Accordion wrapper to JSONPrettyCard
  javascript/src/main/components/Utilities/JSONPrettyCard.js
  javascript/src/test/components/Utilities/JSONPrettyCard.test.js
Labels: READY for STAFF REVIEW, W21-UX Improvements, w21-5pm-1

#191 5pm 3 make total courses sortable
  javascript/src/main/components/Statistics/TotalCoursesTable.js
  javascript/src/main/pages/Statistics/TotalCourses.js
Labels: 10, W21-Statistics, w21-5pm-3

#180 5pm 3 open courses by dept
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/OpenCoursesForm.js
  javascript/src/main/components/Statistics/OpenCoursesTable.js
  javascript/src/main/pages/Statistics/NumOpenCoursesByDept.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/OpenCoursesForm.test.js
  javascript/src/test/components/Statistics/OpenCoursesTable.test.js
  javascript/src/test/pages/Statistics/NumOpenCoursesByDept.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/OpenCourse.java
  src/main/java/edu/ucsb/courses/repositories/ArchivedCourseRepository.java
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/OpenCourseTests.java
Labels: READY for STAFF REVIEW, W21-Statistics, w21-5pm-3

#196 5pm-1 convert admin navbar button into dropdown, add empty admin settings page
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/Admin/AdminSettings.jsx
  javascript/src/test/pages/Admin/Settings.test.js
Labels: 10, Navigation Bar UX Improvements, READY for STAFF REVIEW, W21-UX Improvements, w21-5pm-1

#197 5pm 1 - Move the quarter manipulation code and test to src/main/java/edu…
  src/main/java/edu/ucsb/courses/models/Quarter.java
  src/test/java/edu/ucsb/courses/models/QuarterTests.java
Labels: 20, w21-5pm-1

#195 5pm-4 quarter history column
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/pages/History/CourseName.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
  javascript/src/test/utils/BasicCourseTableHelpers.test.js
Labels: 10, w21-5pm-4

#181 5pm 1 Create new component for courseFilters
  javascript/src/main/components/BasicCourseSearch/CourseFilters.js
  javascript/src/stories/components/BasicCourseSearch/CourseFilters.stories.js
  javascript/src/test/components/BasicCourseSearch/CourseFilters.test.js
Labels: w21-5pm-1

#198 5pm 1 Add courseFilter to Home/CourseName/Ge/Instructor page
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/BasicCourseSearch/CourseFilters.js
  javascript/src/main/fixtures/Courses/BasicCourseTableHelpersFixtures.js
  javascript/src/main/pages/History/CourseName.js
  javascript/src/main/pages/History/Ge.js
  javascript/src/main/pages/History/Instructor.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
  javascript/src/stories/components/BasicCourseSearch/CourseFilters.stories.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
  javascript/src/test/components/BasicCourseSearch/CourseFilters.test.js
  javascript/src/test/pages/History/CourseName.test.js
  javascript/src/test/pages/History/Ge.test.js
  javascript/src/test/pages/History/Instructor.test.js
  javascript/src/test/pages/Home/Home.test.js
  javascript/src/test/utils/BasicCourseTableHelpers.test.js
Labels: 40, W21-UX Improvements, w21-5pm-1

#212 5pm-2 Added spacing to end footer
  javascript/src/main/App.css
Labels: 5, w21-5pm-2

#193 5pm-2 Added an add button column, this button will work in a later issue
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/fixtures/Courses/courseFixtures.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: 40, w21-5pm-2

#208 5pm-4: Download CSV Button Basic Table Component
  javascript/package-lock.json
  javascript/package.json
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/BasicCourseSearch/CourseFilters.js
  javascript/src/main/pages/History/CourseName.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: FIX ME-MISSING TEAM CR, W21-Searches and CSV Download, w21-5pm-4

#211 5pm-2 Show page for personal schedules (Conrad estimates: 20 pts)
  javascript/src/main/App.js
  javascript/src/main/components/Schedule/ScheduleTable.js
  javascript/src/main/pages/Schedule/PersonalSchedule.js
  javascript/src/test/pages/Schedule/PersonalSchedule.test.js
Labels: w21-5pm-2

#215 5pm 2 modify schedule item
  .gitignore
  src/main/.DS_Store
  src/main/java/edu/ucsb/courses/controllers/ScheduleItemController.java
  src/main/java/edu/ucsb/courses/entities/AppUser.java
  src/main/java/edu/ucsb/courses/entities/ScheduleItem.java
  src/main/java/edu/ucsb/courses/repositories/ScheduleItemRepository.java
  src/test/java/edu/ucsb/courses/controllers/ScheduleItemControllerTests.java
  src/test/java/edu/ucsb/courses/entities/ScheduleItemTests.java
Labels: w21-5pm-2

#210 5pm 3 add aggregate statistics page
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Statistics/AggregateStatisticsForm.js
  javascript/src/main/components/Statistics/AggregateStatisticsTable.js
  javascript/src/main/pages/Statistics/AggregateStatistics.js
  javascript/src/main/services/statisticsService.js
  javascript/src/test/components/Statistics/AggregateStatisticsForm.test.js
  javascript/src/test/components/Statistics/AggregateStatisticsTable.test.js
  javascript/src/test/pages/Statistics/AggregateStatistics.test.js
  javascript/src/test/services/statisticsService.test.js
  src/main/java/edu/ucsb/courses/controllers/StatisticsController.java
  src/main/java/edu/ucsb/courses/documents/statistics/AggregateStatistics.java
  src/main/java/edu/ucsb/courses/repositories/ArchivedCourseRepository.java
  src/test/java/edu/ucsb/courses/controllers/StatisticsControllerTests.java
  src/test/java/edu/ucsb/courses/documents/statistics/AggregateStatisticsTests.java
Labels: READY for STAFF REVIEW, W21-Statistics, w21-5pm-3

#216 5pm-4: Added Download Results as CSV to Instructor Page
  javascript/src/main/pages/History/Instructor.js
Labels: READY for STAFF REVIEW, w21-5pm-4

#209 5pm-4: added empty search alerts and test cases
  javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormInstructor.js
  javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
  javascript/src/main/components/BasicCourseSearch/GeCourseSearchForm.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchCourseStartEndQtr.test.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchFormInstructor.test.js
  javascript/src/test/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.test.js
  javascript/src/test/components/BasicCourseSearch/GeCourseSearchForm.test.js
  javascript/src/test/pages/History/Basic.test.js
  javascript/src/test/pages/History/CourseName.test.js
  javascript/src/test/pages/History/Ge.test.js
  javascript/src/test/pages/History/Instructor.test.js
Labels: 20, w21-5pm-4

#217 5-pm-4 Add quarter column to instructor search
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/Statistics/QuarterFormSelect.js
  javascript/src/main/pages/History/Instructor.js
  javascript/src/main/utils/quarterUtilities.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
  javascript/src/test/components/Statistics/QuarterFormSelect.test.js
  javascript/src/test/utils/quarterUtilities.test.js
Labels: FIX ME-please respond to code review, w21-5pm-4

#219 fixed hide/show text issue for JSONPrettyCard. Added JSONPrettyCard …
  javascript/src/main/components/Utilities/JSONPrettyCard.js
  javascript/src/main/fixtures/Utilities/JSONPrettyCardFixtures.js
  javascript/src/stories/components/Utilities/JSONPrettyPanel.stories.js
Labels: READY for STAFF REVIEW, w21-5pm-1

#203 5pm 1 Section and Lecture Background Color, Legend for Search Results
  javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js
  javascript/src/main/components/BasicCourseSearch/TableLegend.js
  javascript/src/main/fixtures/Courses/courseFixtures.js
  javascript/src/main/pages/History/CourseName.js
  javascript/src/main/pages/History/Ge.js
  javascript/src/main/pages/History/Instructor.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/test/components/BasicCourseSearch/BasicCourseTable.test.js
Labels: 20, w21-5pm-1

#220 5pm 1 Fix bug of checking on full in BasicCourseTableHelpers
  javascript/src/main/fixtures/Courses/BasicCourseTableHelpersFixtures.js
  javascript/src/main/utils/BasicCourseTableHelpers.js
  javascript/src/test/utils/BasicCourseTableHelpers.test.js
Labels: READY for STAFF REVIEW, w21-5pm-1
